import './globals.css';
import { Inter } from 'next/font/google';
import { Lexend_Deca } from 'next/font/google';

const inter = Lexend_Deca({ subsets: ['latin'] });

export const metadata = {
  title: 'Mage 9',
  description: 'Generated by create next app',
};

const lexend_deca = Lexend_Deca({
  subsets: ['latin'],
  variable: '--font-lexend_deca',
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={lexend_deca.className}>{children}</body>
    </html>
  );
}
