import Image from 'next/image';
import Head from 'next/head';
import Navbar from '@/components/Navbar';
import TopPart from '@/components/TopPart';
import Competition from '@/components/Competition';
import MediaPartner from '@/components/MediaPartner';
import Footer from '@/components/Footer';
import '../styles/globals.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mage9 | Multimedia and Game Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Navbar />
        <div className="max-w-contentContainer2 mx-auto ">
          <TopPart />
          <Competition />
        </div>
        <div className="max-w-screen min-h-[1000px]">
          <MediaPartner />
        </div>
        <Footer />
      </main>
    </>
  );
}
